[package]
name = "bevyroguelike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6.0", features = ["dynamic"] }
bracket-lib = "~0.8.1"
rand = "0.8.4"
# bevy = "0.6.0"
